package gohttp

import (
	"net/http"
	"strings"
	"sync"
)

type webapplicationfirewall struct {
	http       *http.Response
	raw        string
	exists     bool
	output     string
	solve      string
	firewall   string
	confidence int
}

var wg sync.WaitGroup

// NewFirewallDetectionPassive ::
func NewFirewallDetectionPassive(response *Response) *webapplicationfirewall {
	return &webapplicationfirewall{http: response.Response, raw: response.Raw}
}

func (options *webapplicationfirewall) Cloudflare() *webapplicationfirewall {
	if strings.Contains(options.raw, "Cloudflare Ray ID:") || strings.Contains(options.raw, "Attention Required!") || strings.Contains(options.raw, "DDoS protection by Cloudflare") {
		options.exists = true
		options.output = "Text snippet."
		options.firewall = "Cloudflare"
		options.confidence = 70
	} else if options.http.Header.Get("Server") == "cloudflare" {
		options.exists = true
		options.output = "Header field value."
		options.firewall = "Cloudflare"
		options.confidence = 10
	}

	defer wg.Done()

	return options
}

func (options *webapplicationfirewall) Cerber() *webapplicationfirewall {
	if strings.Contains(options.raw, "We're sorry, you are not allowed to proceed") {
		options.exists = true
		options.output = "Text warning."
		options.solve = "Use the parameter: --tor ."
		options.firewall = "Wordpress Cerber"
		options.confidence = 40
	} else if strings.Contains(options.raw, "Your request looks suspicious or similar to automated requests from spam posting software") {
		options.exists = true
		options.output = "Text warning."
		options.solve = "Set a time for requests with: --http-sleep ."
		options.firewall = "Wordpress Cerber"
		options.confidence = 40
	}

	defer wg.Done()

	return options
}

func (options *webapplicationfirewall) NinjaFirewall() *webapplicationfirewall {
	if strings.Contains(options.raw, "For security reasons, it was blocked and logged") {
		options.exists = true
		options.output = "Text warning."
		options.solve = "Use the parameter: --tor and set a time for requests with: --http-sleep ."
		options.firewall = "NinjaFirewall"
		options.confidence = 40
	} else if strings.Contains(options.raw, "NinjaFirewall") && strings.Contains(options.raw, "NinjaFirewall: 403 Forbidden") {
		options.exists = true
		options.output = "Keyword in title."
		options.solve = "Use the parameter: --tor ."
		options.firewall = "NinjaFirewall"
		options.confidence = 50
	}

	defer wg.Done()

	return options
}

func (options *webapplicationfirewall) Wordfence() *webapplicationfirewall {
	if strings.Contains(options.raw, "Generated by Wordfence") || strings.Contains(options.raw, "This response was generated by Wordfence") {
		options.exists = true
		options.output = "Text snippet."
		options.firewall = "Wordfence"
		options.confidence = 70
	} else if strings.Contains(options.raw, "A potentially unsafe operation has been detected in your request to this site") || strings.Contains(options.raw, "Your access to this site has been limited") {
		options.exists = true
		options.output = "Text warning."
		options.solve = "Set a time for requests with: --http-sleep ."
		options.firewall = "Wordfence"
		options.confidence = 40
	}

	defer wg.Done()

	return options
}

func (options *webapplicationfirewall) BulletProof() *webapplicationfirewall {
	if strings.Contains(options.raw, "If you arrived here due to a search or clicking on a link click your Browser's back button to return to the previous page.") {
		options.exists = true
		options.output = "Text snippet."
		options.firewall = "BulletProof Security"
		options.confidence = 10
	}

	defer wg.Done()

	return options
}

func (options *webapplicationfirewall) SiteGuard() *webapplicationfirewall {
	if strings.Contains(options.raw, "Powered by SiteGuard") || strings.Contains(options.raw, "The server refuse to browse the page.") {
		options.exists = true
		options.output = "Text snippet."
		options.firewall = "SiteGuard"
		options.confidence = 20
	}

	defer wg.Done()

	return options
}

func (options *webapplicationfirewall) All() *webapplicationfirewall {
	wg.Add(6)

	go options.Cloudflare()
	go options.SiteGuard()
	go options.BulletProof()
	go options.Cerber()
	go options.Wordfence()
	go options.NinjaFirewall()

	wg.Wait()

	return options
}

func (options *webapplicationfirewall) Run() (bool, string, string, string, int) {
	if options.exists {
		return options.exists, options.firewall, options.output, options.solve, options.confidence
	}

	return false, "", "", "", 0
}
